### ISSUE TITLE
ignore tags on GH actions build

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvlabox/nuvlabox#17]
add 
```
on:
  push:
    tags-ignore:
      - '*.*.*'
```

on all main.yml, otherwise the nuvladev images will also comprise tag versions.

Repos to be changed:
 - compute-api
 - system-manager

**Comment by cjdcordeiro** [comment]
using:
```
on: 
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*.*'
  pull_request:
  workflow_dispatch:
```
